language: node_js
node_js:
 - "0.12"
install:
 - npm install -g phantomjs@1.9.7-15
 - npm install -g mocha-phantomjs@3.6.0
 - npm install -g gulp@3.9.0
 - npm install
before_script:
 - phantomjs --version
 - mocha-phantomjs --version
 - gulp &
 - sleep 5 # give gulp background task some time to execute.
script:
 - mocha-phantomjs out/test/index.html
 - make test

