language: node_js
node_js:
    - "0.12"
install:
    - npm install phantomjs -g
    - npm install -g mocha-phantomjs
    - npm install -g gulp
    - npm install
before_script:
    - phantomjs -version
    - mocha-phantomjs -version
    - gulp &
    - sleep 5 # give gulp background task some time to execute.
script:
    - mocha-phantomjs out/test/index.html
    - make test

